package com.eagles.day32project;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@MapperScan("com.eagles.day32project.mapper")
public class Day32ProjectApplication {

    public static void main(String[] args) {
        SpringApplication.run(Day32ProjectApplication.class, args);
    }

}
